server:
  port: 9090
spring:
  datasource:
    driver: org.h2.Driver
    password: h2db
    url: jdbc:h2:mem:testdb
    username: h2db
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
plans-api:
     messages:
         plansavesuccess: "Plan Saved Sucessfully"
         plansavefailed: "Plan Saved Failed"
         planupdatesuccess: "Plan Updated Successfully"
         planupdatefailed: "Plan Update Failed"
         plandeletesuccess: "Plan Deleted Successfully"
         plandeletefailed: "Plan Delete Failed"
         planstatussuccess: "Plan status Updated Successfully"
         planstatusfailed: "Plan status not Updated"
